### ISSUE TITLE
Port to Mes?

### ISSUE THREAD

**Issue by Googulator** [schierlm/guile-psyntax-bootstrapping#1]
Would it be possible to port this bootstrap to GNU Mes?

In live-bootstrap, we're currently relying on some pregenerated files in nyacc for running mescc. For a clean bootstrap, these should be regenerated when building Mes - but the process for generating them relies on syntax-case support, which is broken because we currently just delete psyntax.pp without replacement before building Mes.

If psyntax.pp could be bootstrapped in Mes, that would solve the issue of regenerating nyacc's pregen files.

**Comment by schierlm** [comment]
I believe it is possible to "port" this to GNU Mes, but it is a different question whether it is feasible and whether this is the easiest/best way to solve the current dilemma. Keep in mind that while both psyntax implementations have a common ancestor (the Scheme reference implementation of psyntax), the code has diverged quite a bit between how Mes and Guile handle it. In particular, Guile provides primitives for some of the psyntax functions and does not provide native defmacro support, while Mes provides native defmacro support and no primitives for the psyntax functions.

Let me get more into detail.

### Current situation with live-bootstrap

- Live-bootstrap tries to rebuild nyacc grammars using GNU Mes, but without psyntax.pp. As far as I recall, this process involves a single function which is implemented using `syntax-case` where the last two of the case clauses require a fender, i.e. are not trivially portable to syntax-rules, which is supported by GNU Mes without relying on psyntax.pp.
- Timothy Sample (@samplet) (see [chatlogs](https://logs.guix.gnu.org/bootstrappable/2023-08-10.log)) tried to rewrite these two case clauses in a defmacro-style macro, plugging it into the rest of the function, converted the rest to syntax-rules, which made it possible to run the nyacc generator to generate one of the two pregenerated grammar files (tested in mes-gcc) without psyntax.pp, yet the second pregenerated grammar file ran into some bugs (or other weird behaviour) when running it under mes (not under guile). I believe there also was some ranting about stability of macro and syntax-rules implementation in Mes, but I cannot find the chat log link quickly.

### Porting psyntax-bootstrap to Mes

The basic idea of the psyntax bootstrap is:

1.  Try to establish an environment where defmacro-style macros can run without relying on pyntax expansion.
2. port/rewrite some select parts of psyntax.ss from psyntax-style to defmacro-style macros.
3. "Evaluate"/load these macros, and use them to load a stripped down version of the original psyntax.ss file.
4.  The loaded code is used to load the original psyntax.ss file, which in turn is used to load the psyntax expander which is then used to expand the psyntax.ss and print it to psyntax.pp.


(To clarify, these step numbers do not correspond 1:1 to the step files of the bootstrap, but are a bit more high-level overview)

Step 0 (the basic idea how to proceed) is the same.

Step 1 is very easy to port - just rip it out. Mes already has native defmacro support

For Step 2, after identifying the new version of the parts to port in psyntax.ss. there are two approaches. Either compare the psyntax.ss code between Guile and Mes and port the changes over to the version used by the guile bootstrap, or just take the new code and port it "freshly" to use defmacro instead of psyntax. When it is unclear how to port a certain concept from psyntax to defmacro, check how it was done for Guile. My gut feeling tells me that the second "just port it over again" is the easier route, but in any case, who does decides

Step 3 should be pretty straightforward. Identify in the patch what parts to rip out, and rip them out of Mes' psyntax.ss again, making sure not to introduce syntax errors.

Step 4 should be easy, assuming the code to dump psyntax.pp from previous psyntax.pp is preserved somewhere. Just use the new bootstrap instead of old psyntax.pp.

In the process in step 3 or step 4 you might run into bugs in Mes' defmacro / syntax-rules implementation, ending up debugging the same things that samplet tried and (so far) failed. [To be fair, I don't know how much time samplet had available to spend on this project, and how long it took him to give up]. As a bonus, after you solved these issues, there is a high chance be that all the Mes bugs that affected samplet's original code (which uses far simpler macro features than my psyntax bootstrap does) are fixed and you can effectively decide if you want to ditch all your efforts and just use samplet's simpler solution instead.

That being said, in the near future I don't think I can find time to work an any of this. In case I have, I'll focus on samplet's started endeavor and get it to generate the second grammar file on Mes as well. In case they are willing to share their unfinished code, of course.

But ultimately, as always in bootstrapping, who does decides. And I can guarantee you that you will learn more than one new detail about Scheme and macro expansion if you try to go the route of porting my code over (to *any* other psyntax implementation, actually)

**Comment by samplet** [comment]
I have two things to add here:

<ol><li>

[Here's a patch](https://gist.github.com/samplet/78a2e92d47dd37b17886b26dffa14ffd) that applies to NYACC 1.00.2 (from Git) and enables Mes 0.26 to generate the `mach.d` files.  This is relevant to fosslinux/live-bootstrap#306, too.  I could generate the files by running the following from the patched NYACC checkout:

```sh
mes -L module gen-cpp-files.scm
# More RAM for this one!
MES_ARENA=32000000 mes -L module gen-c99-files.scm
mes -L module gen-c99cx-files.scm
```

The patch is pretty ugly, as it works around some missing pieces in Mes.  The main macro change is in `lalr.scm`; the rest of the changes are for other things.

</li><li>

I'm working on `syntax-case` support in Mes.  One of the goals is for Mes to be able to expand Guile's psyntax.  (Another goal is to prevent further macro stability rants!)  I have some working code, but there's a lot of details to sort through.  Not sure about a timeline, but it won't be quick. :snail:

</li></ol>

**Comment by schierlm** [comment]
As the pregen files have been successfully eliminated in live-bootstrap now, I'm closing this issue. Feel free to reopen in case there is any need.
